version: '3'
services:
  frontend:
    image: akhiltavva/frontend:latest
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    image: akhiltavva/backend:latest
    ports:
      - '9091:9090'
    depends_on:
      - database
    # environment:
    
  database:
    image: mysql:latest
    ports:
      - '3307:3306'
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courier_delivery
      MYSQL_USER: root
      MYSQL_PASSWORD: Akhil@0124
    volumes:
      - db_data:/var/lib/mysql  # Persist data to avoid losing database state

volumes:
  db_data: