---
- name: Deploy Delivery Application
  hosts: all
  become: true
  vars:
    ansible_become_pass: "Ansible321@"

  tasks:
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "docker-compose.yml"

    - name: Run Docker Compose
      command: docker-compose up -d